version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:12-alpine
    ports:
     - 5433:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env