# Generated by Django 4.2.17 on 2024-12-05 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_itinerary', '0004_alter_travelitinerary_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelitinerary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
