# Generated by Django 4.2.17 on 2024-12-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_itinerary', '0005_alter_travelitinerary_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('day', models.IntegerField()),
                ('destination', models.CharField(max_length=150)),
                ('accommodation', models.CharField(max_length=150)),
                ('activities', models.CharField(max_length=150)),
                ('actions', models.CharField(max_length=150)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_items', to='travel_itinerary.travelitinerary')),
            ],
        ),
    ]
